---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: end-of-file-fixer

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.17.0
  hooks:
  - id: yamllint
    args: [-c=./.yamllint.yaml]
