title: DevOps Lab 🧪
desc: |
  A Kubernetes home lab deployed entirely with GitOps and defined in YAML.

images:
  - "https://cncf-branding.netlify.app/img/projects/helm/stacked/color/helm-stacked-color.png"
  - "https://info.container-solutions.com/hs-fs/hubfs/GITOPS_icon.png?width=628&height=628&name=GITOPS_icon.png"
  - "https://sdtimes.com/wp-content/uploads/2017/01/0118.sdt-kubernetes.png"

cluster_desc: |
  All deployed applications are defined in the `cluster` directory. Each project is nested
  into the folder that matches their namespace.

cluster_content:
  - "/default      :   A catch-all namespace"
  - "/dev          :   Development tools"
  - "/home         :   Home applications and services"
  - "/games        :   Dedicated game servers"
  - "/monitoring   :   Logging, monitoring, and dashboards"
  - "/kube-system  :   Internal system services"
  - "/flux-system  :   GitOps/Flux operator and services"
  - "/openfaas     :   Open faas serverless resources"

infra_desc: |
  The collection of helm repositories are defined in the `infrastructure` directory.
