version: '3'

tasks:
  default:
    cmds:
      - task: check
    silent: true

  check:
    desc: Run pre-commit checks
    cmds:
      - pre-commit run

  lint:
    desc: Lint YAML files
    cmds:
      - yamllint cluster/**/*.yaml -c ./.yamllint.yaml

  docs:
    desc: Generate README
    cmds:
      - renderizer --settings ".README.yaml" templates/README.tmpl > README.md
