 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRoute
 metadata:
   name: heimdall
   namespace: home
 spec:
   entryPoints:
     - web
   routes:
     - match: Host(`heimdall.local`)
       kind: Rule
       services:
         - kind: Service
           name: heimdall
           namespace: home
           port: 80
