apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: home
spec:
  releaseName: heimdall
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      chart: heimdall
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  values:
    environment:
      TZ: "America/Los Angeles"
