---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.30.100-192.168.30.252
    rbac:
      create: true
    controller:
      image:
        registry: docker.io
        repository: bitnami/metallb-controller
        tag: 0.9.5-debian-10-r5
        pullPolicy: IfNotPresent
      securityContext:
        enabled: true
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
      revisionHistoryLimit: 3
      terminationGracePeriodSeconds: 0
      containerPort:
        metrics: 7472
    speaker:
      image:
        registry: docker.io
        repository: bitnami/metallb-speaker
        tag: 0.9.5-debian-10-r4
        pullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/arch: amd64
