---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: waypoint
  namespace: waypoint
spec:
  releaseName: waypoint
  targetNamespace: waypoint
  interval: 24h
  chart:
    spec:
      chart: waypoint
      version: v0.1.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 24h
