---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: waypoint
  namespace: waypoint
spec:
  releaseName: waypoint
  targetNamespace: waypoint
  interval: 24h
  chart:
    spec:
      chart: waypoint
      version: v0.1.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 24h
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`home-assistant.lan`)
      services:
        - name: home-assistant
          port: 8123
  tls:
    certResolver: default
    options: {}
