---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: agones
  namespace: games
spec:
  releaseName: agones
  targetNamespace: games
  interval: 5m
  chart:
    spec:
      chart: games
      version: v1.14.0-rc
      sourceRef:
        kind: HelmRepository
        name: agones
        namespace: flux-system
      interval: 5m
