---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  releaseName: openfaas
  targetNamespace: openfaas
  interval: 5m
  chart:
    spec:
      chart: openfaas
      version: v7.2.8
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
    functionNamespace: openfaas-fn
    generateBasicAuth: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-ui
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`openfaas.lan`)
      kind: Rule
      services:
        - kind: Service
          name: gateway-external
          namespace: openfaas
          port: 8080
