---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: dev
spec:
  releaseName: argo-workflows
  targetNamespace: dev
  interval: 5m
  chart:
    spec:
      chart: argo
      version: v0.16.10
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: dev
spec:
  releaseName: argo-cd
  targetNamespace: dev
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: v3.2.2
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      interval: 5m
