---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: home
spec:
  releaseName: plex
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      chart: plex
      version: v4.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
