---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  targetNamespace: kube-system
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: v1.1.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: kube-system
spec:
  routes:
    - match: Host(`longhorn.lan`)
      kind: Rule
      services:
        - kind: Service
          name: longhorn-frontend
          namespace: kube-system
          port: 80
