---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: home
spec:
  releaseName: blocky
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      chart: blocky
      version: v3.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blocky-ui
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`blocky.lan`)
      kind: Rule
      services:
        - kind: Service
          name: blocky
          namespace: home
          port: 4000
