---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: monitoring
spec:
  releaseName: heimdall
  targetNamespace: monitoring
  interval: 15m
  chart:
    spec:
      chart: heimdall
      version: v6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: heimdall.lan
          paths:
            - path: /
              pathType: Prefix
              serviceName: heimdall
              servicePort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: heimdall-ui
  namespace: kube-system
spec:
  routes:
    - match: Host(`heimdall.lan`)
      kind: Rule
      services:
        - kind: Service
          name: heimdall
          namespace: monitoring
          port: 80
