---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: v15.4.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-dashboard
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.lan`)
      kind: Rule
      services:
        - kind: Service
          name: prometheus-grafana
          namespace: monitoring
          port: 80
