apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  releaseName: traefik
  targetNamespace: kube-system
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: v9.19.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    rbac:
      enabled: "true"
    ssl:
      enabled: "true"
    metrics:
      prometheus:
        enabled: "true"
    kubernetes:
    namespaces:
      - default
      - kube-system
      - games
      - home
      - monitoring
    ingressEndpoint:
      useDefaultPublishedService: "true"
    image:
      name: "rancher/library-traefik"
    dashboard:
      enabled: "true"
      domain: "traefik.local"
