---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  releaseName: kubeapps
  targetNamespace: kubeapps
  interval: 24h
  chart:
    spec:
      chart: kubeapps
      version: v7.5.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: kubeapps
      interval: 24h
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: kubeapps.lan
          paths:
            - path: /
              pathType: Prefix
              serviceName: kubeapps
              servicePort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubeapps-ui
  namespace: kube-system
spec:
  routes:
    - match: Host(`kubeapps.lan`)
      kind: Rule
      services:
        - kind: Service
          name: kubeapps
          namespace: kubeapps
          port: 80
