---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  releaseName: kubeapps
  targetNamespace: kubeapps
  interval: 24h
  chart:
    spec:
      chart: kubeapps
      version: v7.5.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  values:
    ingress:
      enabled: true
      tls: true
      hostname: kubeapps.lan
      selfSigned: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: kubeapps.lan
          paths:
            - path: /
              pathType: Prefix
              serviceName: kubeapps
              servicePort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubeapps-ui
  namespace: kube-system
spec:
  routes:
    - match: Host(`kubeapps.lan`)
      kind: Rule
      services:
        - kind: Service
          name: kubeapps
          namespace: kubeapps
          port: 80
  tls:
      - hosts:
            - kubeapps.lan
        secretName: kubeapps-local-cert-tls
