---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: dev
spec:
  releaseName: drone
  targetNamespace: dev
  interval: 5m
  chart:
    spec:
      chart: drone
      version: v0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
      interval: 5m
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: drone
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`drone.lan`)
      priority: 10
      services:
        - name: drone
          port: 80
  tls:
    certResolver: default
    options: {}
