---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  releaseName: cert-manager
  targetNamespace: kube-system
  interval: 24h
  chart:
    spec:
      chart: cert-manager
      version: v1.6.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 24h
