---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: micro
  namespace: micro
spec:
  releaseName: micro
  targetNamespace: micro
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
        retries: 3
  chart:
    spec:
      chart: micro
      version: v1.2.1
      sourceRef:
        kind: HelmRepository
        name: micro
        namespace: flux-system
      interval: 5m
