---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  releaseName: minecraft
  targetNamespace: minecraft
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: v3.1.6
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
      interval: 5m
  values:
    minecraftServer:
      difficulty: easy
      eula: true
      serviceType: LoadBalancer
    persistence:
      annotations:
        storageClass: longhorn-static
      dataDir:
        enabled: true
        Size: 1Gi
