---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  releaseName: minecraft
  targetNamespace: games
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: v3.1.6
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
      interval: 5m
  values:
    minecraftServer:
      difficulty: hard
      eula: true
      serviceType: LoadBalancer
