apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: home
spec:
  releaseName: adguard
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namepace: home
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
