apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: home
spec:
  releaseName: adguard
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: v3.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
