apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: home
spec:
  releaseName: adguard
  targetNamespace: home
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: adguard-home
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
