---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: home
spec:
  releaseName: adguard
  targetNamespace: home
  interval: 15m
  chart:
    spec:
      chart: adguard-home
      version: v3.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
    service:
      type: LoadBalancer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-ui
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`adguard.lan`)
      kind: Rule
      services:
        - kind: Service
          name: adguard-adguard-home
          namespace: home
          port: 3000
