---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: home
spec:
  releaseName: jupyterhub
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      chart: jupyterhub
      version: v0.11.1
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jupyterhub-ui
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jupyter.lan`)
      kind: Rule
      services:
        - kind: Service
          name: jupyterhub
          namespace: home
          port: 8080
